site_name: Aurora Creation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: deep purple
      accent: orange
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: deep purple
      accent: orange

plugins:
  - social
  - search
  - glightbox

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://www.linkedin.com/company/aurora-creation
    - icon: fontawesome/brands/twitter
      link: https://www.linkedin.com/company/aurora-creation
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/aurora-creation

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/KonradAurora"  target="_blank" rel="noopener">Aurora Creation</a>